server:
  port: 9090
#management:
#  metrics:
#    web:
#      server:
#        auto-time-requests: false
#spring:
#  application:
#    name: aaaaa
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  #      注册中心访问地址
#  instance:
#    prefer-ip-address: true
#spring:
#  main:
#    allow-bean-definition-overriding: true
##    是否将当前服务的IP注册到Eureka