server:
  port: 9010
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YanMao186/springCloud.git
          searchPaths: config   #配置仓库路径
          username: YanMao186
          password: Gh18392585383
      label: master   #配置仓库分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false
#    fetch-registry: false
#  eureka.client.register-with-eureka=false
#  eureka.client.fetch-registry=false