server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      client:
        enable: true
#        设置开启请求跟踪
    sampler:
      probability: 1.0
#      设置采样比例，默认1.0
  zipkin:
    base-uri: http://localhost:9090/
#    zipkinServer地址
eureka:
  client:
    service-uri:
      defaultZone: http://localhost:8761/eureka/