server:
  port: 9003
spring:
  application:
    name: gateway
#  main:
#    allow-bean-definition-overriding: true
  #当遇到同样名字的时候，是否允许覆盖注册
#解决Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true异常
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    provider: /p/**
#      给服务提供者provider设置映射需要访问时http://localhost:9003/p/person/*